### PR TITLE
Feature auto pingdom sg and add infra creation

### PR DESCRIPTION
**Pull request by gellner**
Automatically add pingdom security groups (with the Europe probe server IPs) when API or Ingress lockdown is enabled, and parameter pingdomAllowed is True

Pingdom security groups are static until automation is implemented to keep them up to date.

Additionally, this PR moves the creation of the infra machineset, secret and MachineConfigPool into the deployment code; this means that the machineset can include the infra server antiaffinity group correctly and the pingdom ingress group can be included if necessary.

There is a matching PR in the openshift-v4 repo to remove the parts of post-deployment that are now unnecessary.

Note that there is still no way of deploying a cluster without infra nodes (but this was an issue with the previous code too...)

### CODE REVIEW

**Comment by gellner** [comment]
Tested with v4.7.1 and v4.7.7

**Comment by andrew-garner** [comment]
Could you please add something to the README to say what version of Ansible this works with. I see you've added importing community.general into the Galaxy requirements.yml and used syntax which I think implies this has been run with Ansible 2.10.x (and not 2.9, Collections weren't GA then, or 3.0 which I think includes the community.general collection).

**Review by andrew-garner — COMMENTED** [review]
The code in here all looks good to me.

**Review by andrew-garner — APPROVED** [review]
Readme update looks great, PR approved from me.

**Review by andrew-garner — APPROVED** [review]
Still approved :)

**Pull request merged**
